name: Module version change check

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 19.0

jobs:
  ensure_module_version_changed:
    runs-on: ubuntu-latest
    name: Ensure module version changed
    steps:
      - uses: actions/checkout@v7
      - name: Ensure module version changed
        id: changed-files
        with:
          dir_names: true
          dir_names_exclude_current_dir: true
          dir_names_max_depth: 1
          files_ignore: '.*'
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96
      - name: List all changed modules
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for dir in ${ALL_CHANGED_FILES}; do
            echo "$dir was changed"
            if [ -f "${dir}/__manifest__.py" ]; then
              version_in_branch=$(grep 'version' "${dir}/__manifest__.py" | awk '{print($2)}')
            fi
            echo "${version_in_branch} in branch"
          done



